sudo: required

language: python

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - docker --version
  - docker build -t nginx-reverse-proxy-stdout .
  - docker tag nginx-reverse-proxy-stdout $DOCKER_USERNAME/nginx-reverse-proxy-stdout
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/nginx-reverse-proxy-stdout:latest
